### ISSUE TITLE
at.js support editor of Ueditor problem

### ISSUE THREAD

**Issue by linjiqin** [ichord/At.js#161]
at.js currently supported CKEditor TinyMCE, I used in the project of at.js and Ueditor, can let the at. js also supports Ueditor. Want there to be honored to get your reply, my E-mail is 416501600@qq.com.

Ueditor is a web editor, website is http://ueditor.baidu.com/website/

**Comment by zywj** [comment]
请问上面的代码，在下拉菜单时，用鼠标选中，不会在后面添加空格是什么原因

**Comment by ichord** [comment]
@zywj 最好能用 jsfiddle 之类的给我重现一下，不然我也不好找。

**Comment by zywj** [comment]
@ichord 请看这里  http://runjs.cn/detail/yzpcz8us

**Comment by zywj** [comment]
@ichord 需要vpn或代理，我调用了google外链
