### ISSUE TITLE
How create AJAX request, if I have very many users?

### ISSUE THREAD

**Issue by aiiddqd** [ichord/At.js#165]
Hi!
Thx for great component!

I have big site with over 1000 users.
Just load AJAX runs long. I want to boot with this selection of 2 or more characters. to reduce the load and speed up.

ps I bad speak English )

**Comment by martec** [comment]
for me this link https://github.com/ichord/At.js/wiki/How-to-use-remote_filter not work.

**Comment by grmarcil** [comment]
Seems the page has been renamed: https://github.com/ichord/At.js/wiki/How-to-use-remoteFilter

**Comment by martec** [comment]
@grmarcil 
thanks very much!
exactly what I needed.
