### ISSUE TITLE
IE10, suggestion dropdown gets misplaced

### ISSUE THREAD

**Issue by vahtel** [ichord/At.js#191]
The dropdown box gets placed somewhere at the bottom of the screen. It's broken with IE9 and IE10, see the screenshot. Tested from the demo site http://ichord.github.io/At.js/.
![ie10](https://cloud.githubusercontent.com/assets/396759/3787652/583aa2ba-1a29-11e4-9eb6-2f1bbc3c4567.jpg)

**Comment by ichord** [comment]
No planning to fix this bug.
