### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.

### ISSUE THREAD

**Issue by thejchap** [ichord/At.js#192]
Happens when the 'at' is first inserted in the area, and again on every subsequent match against the data.

Investigating more, but figured id open as it's occurred in 2 totally different use cases (standalone on a contenteditable div, and with CKEDITOR)

**Comment by xupeng881219** [comment]
Maybe you could try to set "FCKConfig.StartupFocus" to "true" in the "fckconfig.js".
