### ISSUE TITLE
TypeError: Cannot read property 'text' of null

### ISSUE THREAD

**Issue by jacquescrocker** [ichord/At.js#235]
I'm seeing a lot of `TypeError: Cannot read property 'text' of null`

specifically `query` is null, so wherever it uses `query.text`, it errors out

latest version (0.5.2) with latest caret.js

**Comment by alagos** [comment]
I'm having this issue also using v1.5.3

My problem is, I can't reproduce this bug, I've just seen the reports recorded in sentry, from Chrome 58.0.3029 and Chrome mobile 58.0.3029 users (not sure if is something related with this browser or they simply uses Chrome), but the line where is failing is [this one](https://github.com/ichord/At.js/blob/a42065e64d67cb85c396a256627a3b72626b6f9d/src/controller.coffee#L84).
I'm using it with react and here's the relevant code:

```js
  componentDidUpdate(prevProps, prevState) {
    const textarea = $(this.refs['answer-' + this.props.id]);
    if (textarea.data("atwho") == undefined) {
      textarea.atwho({
        at: "@",
        data: this.state.macros,
        displayTpl: "<li><b>@${name}: </b><div>${description}</div></li>",
        insertTpl: "${description}",
        delay: 400
      }).atwho('run');
    }
    textarea.focus();
    textarea.off("inserted.atwho");
    textarea.on("inserted.atwho", this.setMacroToAnswer.bind(this));
  }

  setMacroToAnswer(event, flag, query) {
    this.setState({answer: this.refs['answer-' + this.props.id].value});
  }

```
```jsx
              <textarea name='answer' type="text" className="form-control"
                        placeholder="Type an answer" rows='4' cols='80'
                        ref={`answer-${this.props.id}`} value={answer}
                        onChange={this.handleInputChange}
                        onKeyDown={this.checkCtrlEnter} disabled={locked} />
```
The content of `this.state.macros` is something like:
```
    [
      {
        "description": "Something",
        "id": 63,
        "name": "something"
      },
    ]
```
Just to notice this is working for me locally and in production, but sometimes is not working for some people for some unknown reason.
