### ISSUE TITLE
At.js with RequireJS SPA (made with DurandalJS)

### ISSUE THREAD

**Issue by rhulshof** [ichord/At.js#241]
Using the following `shim` config:

```
shim: {
    'caret'            : ['jquery'],
    'atwho'            : ['jquery', 'caret'],
    'bindings/mention' : ['atwho']
}
```

And the following Binding Handler namespaced as `bindings/mention`:

```
define(function()
{
	var $			= require('jquery');
	var ko			= require('knockout');
    var atwho		= require('atwho');

    ko.bindingHandlers.mention = {
		init: function(element, valueAccessor, allBindingsAccessor, context)
		{
			var lists = valueAccessor().data;

			$(element).atwho({
				at		: '@',
				data	: lists,
				tpl		: "<li data-value='@${username}'>${name} <small>@${username}</small></li>"
			});

			ko.utils.domNodeDisposal.addDisposeCallback(element, function(e)
			{
				$(element).atwho('destroy');
			});
		}
    };
});
```

The first page I view, contains several (5) input fields that have At.js attached. It works absolutely great. But, as soon as I go to another page, At.js stops working. I've tried to backtrace the problem, and this is what I found. (i don't use coffeescript, so my research was done on the dist file)

On the first page (that is working correctly) `Controller.prototype.lookUp` can correctly use `this.catchQuery(e)` because at that moment in time the `TextareaController` contains as follows:

```
TextareaController.query = {
   endPos : 8
   headPos : 1,
   text : "Testing" // I mentioned @Testing for testing purposes
}
```

However, when I go to another page and the Atwho plugin stops working, it looks as follows:

```
TextareaController.query = null
```

Because the `TextareaController.query` is empty, the following code in the `Controller.prototype.lookUp` method prevents the `TextareaController.query` from every being set:

```
if (!(query = this.catchQuery(e))) {
  return;
}
```

Whenever I optimize Durandal; a.k.a. replace RequireJS with Almond, the Atwho plugin stops working on all pages. Even the first. This is caused by the same issue as described above.

Hopefully this report is useful to you?

**Comment by ichord** [comment]
I'm afraid that I have to work on it at this weekend; sorry about it.

**Comment by rhulshof** [comment]
Ok @ichord! Thank you for looking into it. I am looking forward to the fix. If I can be of any assistance, please let me know.

**Comment by ichord** [comment]
I would be appreciated if you can set up a demo for me to debug. It takes me so much time to setup a demo before i can examine it.
If it works at first loading, it could be the problem that is related to page loading.

**Comment by ichord** [comment]
If there were no errors being thrown and it called `lookUp` function, i think you could try to figure out why the `catchQuery` function return null.

**Comment by rhulshof** [comment]
While setting up a demo environment to reproduce the issue, I got a different javascript notice that eventually led to the solution:

In `jquery.atwho.js`, replace the following line:

```
define(["jquery"], function ($) {
```

With:

```
define(["jquery", "caret"], function ($, caret) {
```

That's it! :-)

**Comment by ichord** [comment]
Actually, You don't need the shim, for caret.js supports AMD loading.
You could remove the shim and require 'caret' before 'atwho':

```javascript
    var $ = require('jquery');
    require('caret');
    require('atwho');
    var ko = require('knockout');
```

After requiring 'caret' and 'atwho' , they will attach to `$.fn`.
close it if it could solve the problem, thanks.

**Comment by rhulshof** [comment]
I use the shim to make sure that CaretJS is included in the optimized build before AtJS. If I do as above, its order in the optimized build is not guaranteed. In other words, it will work correctly when using RequireJS, but when optimizing into AlmondJS, it's not guaranteed to work correctly anymore.

**Comment by rhulshof** [comment]
I tested your suggestion, but it doesn't work without `shim`-ing it.

Besides that, adding `caret` as a dependency in the `atwho` library, is part of correct AMD behavior.
