### ISSUE TITLE
remoteFilter results in undefined

### ISSUE THREAD

**Issue by themerius** [ichord/At.js#242]
Hi there,

I'm trying to use remoteFilter with v1.0.0. My code looks somehing like this:

      $('#dict').atwho({
        at: ":",
        callbacks: {
          remoteFilter: function(query, callback) {
            $.getJSON("/search", {q: query}, function(data) {  // /search returns a json-structure
              console.log(data.items, query)  // in data.items is an string array, for example ['x', 'y', 'z', 'a']
              callback(['x', 'y', 'z', 'a']) // for easy testing I'll use the array instead of data.itmes
            });
          }
        }
      });

If I now trigger the `at`, it shows four `undefined` instead of x, y, z and a. But console.log shows the correct array, so I'll assume it's correcly loaded via ajax.

Is something wrong with my code? I have overseen something?

Thank you very much!

**Comment by ichord** [comment]
Oh. the default data structure should be :

```json
[{name: "one", name: "two", name: "three"}]
```

**Comment by ichord** [comment]
The fix can let the `callback` accept an array.

**Comment by themerius** [comment]
Thank you, works great!
