### ISSUE TITLE
Allow results to be grouped and sorted by group

### ISSUE THREAD

**Issue by brendanheywood** [ichord/At.js#244]
We are using Select2 and At.js side by side and love them both for different use cases. We use the same api endpoints for both lookups and for each result has an optional group, and each group is prioritised. 

So for our Select2 dropdowns we can get stuff like this:
![image](https://cloud.githubusercontent.com/assets/187449/5695035/0a3123b0-99df-11e4-9085-0e0d65098ad7.png)

I'd love to be able to get the same result with at.js.

**Comment by ichord** [comment]
If the `data` is a plain object and its structure looks like this:

```json
{
    "goup one": [
        {id: 1, name: "hello", something: "else" },
    ],
    "group two": [{}]
}
```

The dropdown view would be rendered in group view.

**Comment by brendanheywood** [comment]
Cool - however the groups need to be ordered as well as the items in each, so perhaps something more like:

```javascript
[
  {
    name: "group one",
    items: [
      {id: 1, name: "hello", something: "else" },
    ],
  },
  {
    name: "group two",
    items: [
      ....
    ]
  }
]
```

I'd guess you'd also want a groupTpl option as well

**Comment by houd1ni** [comment]
Does anybody works on this? Is there any code for this now?

**Comment by ichord** [comment]
@houd1ni no.

**Comment by houd1ni** [comment]
Then I'll try to make some sketches after working on #262, following this topic.

**Comment by ichord** [comment]
sorry, no more new feature.

**Comment by brendanheywood** [comment]
Any reason?

**Comment by ichord** [comment]
sorry that I'm too busy to fix bugs and I'm busy on working too.

**Comment by houd1ni** [comment]
Probably, I will have a time after these one-two weeks, and then make some enhancements/fixes.
Keep looking there and on the pull requests: you're always able to use a branch until it will be merged.

**Comment by ichord** [comment]
@houd1ni so I reopened it for you, thank you very much.

**Comment by ichord** [comment]
close for keeping simple.
