### ISSUE TITLE
Start autocompleting from start of field value without @

### ISSUE THREAD

**Issue by adam-lynch** [ichord/At.js#246]
I wonder would it be possible to set this up so it could be used as autocomplete for anything that is put in a field at the beginning; i.e. if I put in `a` at the start of the field then it'll show a list of things containing `a`. If I put in a space and then `b`. it'll look for `a b` in the list. So just one suggestion list per field and no `@` needed. My use case is for people's names. We already use At.js and we need this new autocompleted field to *feel* the same.

I've been trying to bend [jQuery-autoComplete](https://github.com/Pixabay/jQuery-autoComplete) into what I need (what I described above) but after a few issues and PRs, it's still not close to this (and the owners [aren't onboard with obviously worthwhile changes](https://github.com/Pixabay/jQuery-autoComplete/issues/6)).

**Comment by ichord** [comment]
At.js use the `matcher` callbacks to match the string such as `@xxx` , so that you can write your own matcher to return whatever string you want to match. for example, just return the whole:

```javascript
        matcher: function(flag, subtext) {
          return subtext;
        }
```
It will popup the menu when the text field is focus.

**Comment by adam-lynch** [comment]
Hmm. cc @4ver
