### ISSUE TITLE
Wrong positioning due to long text wrapping

### ISSUE THREAD

**Issue by romaincointepas** [ichord/At.js#247]
Hi,

First, great library, thanks for this!

I'm encountering a positioning bug with a textarea, probably due to some wrapping of long text (in my case, links).

Here is when it works:
![screen shot 2015-01-30 at 5 21 19 am](https://cloud.githubusercontent.com/assets/797899/5976203/1559f3a6-a840-11e4-8aee-4d89bb3f0722.png)

And when it fails (AFTER the link pushed to a new line):
![screen shot 2015-01-30 at 5 21 03 am](https://cloud.githubusercontent.com/assets/797899/5976213/235c57a0-a840-11e4-8bdc-828718e42b88.png)

Any idea how to solve this?

PS: viewport is very wide, I just cropped the interesting part only, so it's not a repositioning of some sort.

Thanks!

**Comment by ichord** [comment]
@romaincointepas  please use Caret.js#master to check if it solve your problem. Then i will release a new hotfix version.

**Comment by romaincointepas** [comment]
@ichord Tried using master of Caret.js, doesn't seem to fix the problem :/

You can reproduce (before your fix, production caret.js) here: http://www.twitshot.com/?text=Dribbble%20-%20Hixle%20Dashboard%20by%20Balraj%20Chana&url=https%3A%2F%2Fdribbble.com%2Fshots%2F1890201-Hixle-Dashboard (try typing @... right after the link).

BTW, I'm using Google Chrome 40, stable channel on OS X Yosemite.

**Comment by ichord** [comment]
I'm using the same browser( Chrome 40) and OS, It's how i saw by simulating your text.
There just one line text.

![screen shot 2015-02-03 at 8 03 25 pm](https://cloud.githubusercontent.com/assets/1324791/6019843/047765a2-abe0-11e4-8ec0-9b09c815f309.png)

Let me have try on that link later, I can't access it now. (I'm in china, and the VPN is not working on my 3G router)

**Comment by ichord** [comment]
BTW. You can play around on http://ichord.github.com/Caret.js , I have updated it for that fix.
Basically, this is the problem of Caret.js; if Caret.js work fine, then At.js would be fine too.

**Comment by romaincointepas** [comment]
I can't reproduce on At.js or Caret.js example pages. Waiting for your feedback when you can access twitshot.com (I've tried playing around css properties, like box-sizing, nothing).

Ah, other people can also reproduce (I wanted to make sure it wasn't just on my machine).

**Comment by ichord** [comment]
...... You might not be using the right Caret.js file, I download the whole page and just replace the min file and it work fine.

![screen shot 2015-02-03 at 10 42 34 pm](https://cloud.githubusercontent.com/assets/1324791/6022162/fb55c7c8-abf5-11e4-8ed6-6ea6da24ca8a.png)

Please make sure you are using the newest one, which must have this codes https://github.com/ichord/Caret.js/commit/e575bdc16e3f253776198b369cbec419c478c55b
If the problem still exist (it can't be....), and you can't reproduce it on any demo page, please provide me a available demo.

**Comment by romaincointepas** [comment]
@ichord My bad, it works (don't know what I did wrong the first time I tested).

Thank you for being this quick and sharp on fixing this!
