### ISSUE TITLE
atwho-inserted tag removed with backspace

### ISSUE THREAD

**Issue by vahtel** [ichord/At.js#250]
I would like to style the at who-inserted tag but it gets removed when you press backspace.

The use case is when you insert multiple username and want to separate them with commas. 
Example: @user1, @user2 and @user

When you select a value from the dropdown it gets inserted and there is a whitespace at the end. To add a comma you need to delete the whitespace with backspace. But doing that removes the atwho-inserted tag.

I can't use a comma as a suffix because it's only there sometimes. 

It doesn't work with Chrome, Safari, IE11.
It works with Firefox.

**Comment by ichord** [comment]
It's confused. But the `afterMatchFailed` callback might help you, here was an example: [new hashtags](https://github.com/ichord/At.js/blob/master/examples/hashtags.html) 
That demo show you how to create a new tags which not in the list.

**Comment by vahtel** [comment]
OK, thanks. I'll check it out.

**Comment by ichord** [comment]
close for now.

**Comment by vahtel** [comment]
It works, except when the name has "." in it. Here's an example http://jsbin.com/nuhiza/2/ , type "#jac" to insert "Jac.ob" . Then press backspace twice to add a comma. You'll get this error:

[Error] TypeError: null is not an object (evaluating 'this.query.el')
	insert (jquery.atwho.js, line 587)
	afterMatchFailed (2, line 36)
	catchQuery (jquery.atwho.js, line 564)
	lookUp (jquery.atwho.js, line 346)
	(anonymous function) (jquery.atwho.js, line 156)
	map (jquery.min.js, line 4)
	dispatch (jquery.atwho.js, line 145)
	onKeyup (jquery.atwho.js, line 185)
	(anonymous function) (jquery.atwho.js, line 107)
	dispatch (jquery.min.js, line 5)
	handle (jquery.min.js, line 5)


Any pointers ?

**Comment by ichord** [comment]
The matcher did not match `.` , but it will match now for it seems a common case.
But if there is some others char that matcher wouldn't match, this problem will appear again; and then you have to override the matcher to match that.

Then you can do this hack to solve your problem:

```javascript
        afterMatchFailed: function(at, el) {
          if (at == '#') {
            text = el.text().trim();
            // dirty hack:
            $("#editable").atwho({at: at, suffix: ","});
            this.insert("<b>" + text.substr(0,text.length-1) + "</b>");
            $("#editable").atwho({at: at, suffix: null});
            return false;
          }
        }
```

**Comment by ssshake** [comment]
I replaced the suffix of a space with a zero width space and that seemed to help a lot. Opinions?

    at: '@',
    suffix: '\u200B',
    spaceSelectsMatch: true,
