### ISSUE TITLE
Where to add desktop client which uses At.js?

### ISSUE THREAD

**Issue by adam-lynch** [ichord/At.js#251]
[TeamworkChat](http://www.teamwork.com/chat) uses At.js. I'm not sure how I should add it to the [Sites](https://github.com/ichord/At.js/wiki/Sites) wiki page though. Right now, there's just Windows & Mac desktop clients. So no "site" really. 

( Coming soon are iOS & Android apps, a Linux desktop app, a web version and another web version I can't talk about yet :) )

Examples:

![screen shot 2015-02-09 at 21 42 31](https://cloud.githubusercontent.com/assets/1427241/6116452/95e58bae-b0a4-11e4-8b20-d238dfe2663b.png)

![screen shot 2015-02-09 at 21 31 06](https://cloud.githubusercontent.com/assets/1427241/6116432/72591dea-b0a4-11e4-9ddc-d38150534686.png)

**Comment by ichord** [comment]
Wow, That is pretty cool!
Thanks for putting your product in the list ( `sites` ), it's my pleasure.
I changed the `sites` to [Products using At.js](https://github.com/ichord/At.js/wiki/Products-using-At.js), how about it?

**Comment by ichord** [comment]
BTW. I'm meeting you team (on your website.). :smile:

**Comment by adam-lynch** [comment]
Done. Keep up the good work :D
