### ISSUE TITLE
官网的demo，@之后中文输入不了呀

### ISSUE THREAD

**Issue by pcxiong** [ichord/At.js#252]
Mac,  搜狗, contenteditable, 我想在@之后输入“中”字，Chrome 会成这个样子，Firefox不会 ：

![image](https://cloud.githubusercontent.com/assets/9209882/6166271/ba261d02-b2e9-11e4-9acf-fc6298d2b8cb.png)

请问是我哪里操作错了？
谢谢哦。

**Comment by yejingx** [comment]
我也碰到这个问题，叫结中。好像从0.5.2之后就有这个问题了

**Comment by ichord** [comment]
我试了没有问题啊，你们用的是什么操作系统？

**Comment by pcxiong** [comment]
咦？我是 10.9 ，屡试不爽，你那没法复现？

**Comment by ichord** [comment]
well. I found it. It's a bug.

**Comment by ichord** [comment]
已在 master 分支修复并更新了官网 demo 页，可以去试试。

**Comment by pcxiong** [comment]
多谢，新年快乐

**Comment by ichord** [comment]
新年快乐. :)

**Comment by pcxiong** [comment]
啊。。。真是抱歉。。。
![image](https://cloud.githubusercontent.com/assets/9209882/6252468/9b905c86-b7d5-11e4-8f0c-a02805df6357.png)
“中”字确实可以了，可是中文的“文”，敲了"w"之后就这样了。。。其实测试之后发现，@之后第二个汉字，任意汉字都输不进去。。。

**Comment by ichord** [comment]
... 待我来个彻底的解决方法.
