### ISSUE TITLE
Doesn't work with Froala editor

### ISSUE THREAD

**Issue by vahtel** [ichord/At.js#253]
I'm trying to get it working with Froala editor (https://github.com/froala/wysiwyg-editor) but there is an error:
jquery.atwho.js:542 Uncaught InvalidNodeTypeError: Failed to execute 'surroundContents' on 'Range': the given Node has no parent.

It happens after you have typed "@". Here's the test case http://jsbin.com/lajuni , try typing "@" .

**Comment by deronsizemore** [comment]
I'm getting the same behavior in Froala. Would love to be able to use this with Froala if there's some kind of an easy fix.

**Comment by Georg7** [comment]
+1 getting exact same behaviour. Any ideas/suggestions for a fix?

**Comment by ichord** [comment]
Ooops... wrong reference.

**Comment by stefanneculai** [comment]
I checked this and it seems that there is a small change that should be made to At.js in order to get it work with Froala Editor. At.js wraps the range with a `<span>`. Because Webkit browsers might add unwanted spans, new spans are accepted into the editor only if they have the attribute `data-fr-verified="true"`. I believe it would be good to make the query string a variable / option.

Changing 
```js
range.surroundContents(($query = $("<span class='atwho-query'/>", this.app.document))[0]);
```
to
```js
range.surroundContents(($query = $("<span class='atwho-query' data-fr-verified=true/>", this.app.document))[0]);
```
will make this work (See http://jsbin.com/xufosinuru/2).

**One suggestion**: I think it would be good to allow overriding methods of the plugin. I could test easier if there was a way to override the `EditableController.prototype.catchQuery`. Unfortunately, I couldn't find a way to do that.

**Comment by Georg7** [comment]
That did it, thanks @stefanneculai

**Comment by deronsizemore** [comment]
worked for me too! Thanks @stefanneculai

**Comment by ichord** [comment]
Please have a try on `editableAtwhoQueryAttrs` options to attach `data-fr-verified` to `.atwho-query` element before it's inserted.

**Comment by deronsizemore** [comment]
Thanks @ichord

**Comment by ichord** [comment]
@stefanneculai Thanks your works and the suggestion. 
It would be better to just modify the source code if overriding methods is for test.
If there still lots of hacks have to be done for `EditableController`, I would expose it.

**Comment by stefanneculai** [comment]
I believe that `editableAtwhoQueryAttrs` does the job. :+1:

**Comment by aligajani** [comment]
Hey guys..I am using Froala with Atjs and it doesn't work. It doesn't show at all.

If I place a samplet textarea, then it works.

**Comment by deronsizemore** [comment]
@aligajani did you try all of the suggestions above? If so, it may be hard to tell as I know Froala has been updated since my original post which may have changed some things with regards to At.js and how it works with Froala.

**Comment by aligajani** [comment]
@deronsizemore  I initially thought the issue was z-index but that seems to be not the issue. At the core, it just doesn't appear on screen. Froala is blocking it perhaps. I am supplying atjs the id of the text area contained inside the froala wrapper.

**Comment by stefanneculai** [comment]
A working jsFiddle: http://jsfiddle.net/8myoLgLy/4/

**Comment by aligajani** [comment]
Wow, why doesn't it work on mine though. Here's some data you might find helpful. 

```
<script>
         $('#edit').atwho({
             at: "@",
             data:['Peter', 'Tom', 'Anne'],
             editableAtwhoQueryAttrs: {"data-fr-verified": true}
         })
     </script>
```

http://d.pr/i/17hew

**Comment by deronsizemore** [comment]
Thanks @stefanneculai for that Fiddle. I may definitely give this a try again as it looks like it works great and is less buggy than what i'm using at the moment. I just need to figure out how to add some images into the mention dropdown and I'll be good.

**Comment by aligajani** [comment]
Doesn't work with mine though. What could be wrong, using latest versions of all libs. I also tried to make it work on a textarea seperate from my Froala, it worked then.

**Comment by aligajani** [comment]
Guys @deronsizemore @stefanneculai , what could be wrong with mine. It doesn't seem to work on a froala element at all.

**Comment by deronsizemore** [comment]
@aligajani Hard to tell by looking at your screenshot but the code you supplied looks like you're targeting #edit which is a textarea. Have you attempted to target the Froala id/class instead?

**Comment by aligajani** [comment]
Yeah I have targetted 'froala-element' too bud.

**Comment by deronsizemore** [comment]
Any errors in console? Can you view source and ensure that the JS files are included correctly and that you can open them?

**Comment by aligajani** [comment]
as I said, it works if I run it on a plain textarea. No errors in console either.

**Comment by deronsizemore** [comment]
I understand that. Just trying to run through all the usual troubleshooting steps that I typically do. I'm not sure then if you're able to get it going on a textarea and no errors. I'm out of ideas.

**Comment by aligajani** [comment]
By the way, @deronsizemore , I get Froala to launch using this

```
{{ Form::textarea('text', '', array('id' => 'edit', 'class' => 'form-control', 'placeholder' => 'Your words go here..', 'data-parsley-required' => 'true', 'data-parsley-trigger' => 'change', 'data-parsley-minlength' => '10', 'size' => '60x10')) }}
```

Then I use `('#edit').editable to trigger it. Maybe that's the issue?

**Comment by aligajani** [comment]
Looks like Froala isn't letting me trigger any kind of JS, I tried binding events to it too?

**Comment by rjsmith** [comment]
Hi @stefanneculai  Looks like this workround for Froala Editor has broken in V2 .  See this fiddle using Froala Editor V2:

http://jsfiddle.net/rj_smith/og18qLza/

I just updated your fiddle from your comment above https://github.com/ichord/At.js/issues/253#issuecomment-135509610 using the V2 code.

I would be really grateful if you could suggest how to get this working in V2 again ....

**Comment by rjsmith** [comment]
Hmm, I have now got the Atwho menu appearing (by initialising it on the 'div.fr-view' element), but when I select an item, it does not get inserted into the editor DOM, instead it adds a blank line:

http://jsfiddle.net/rj_smith/og18qLza/8/

```javascript
var config = {
    at: "@",
    data: names,
    editableAtwhoQueryAttrs: {
        "data-fr-verified": true
    },
    displayTpl: "<li>${name} <small>${email}</small></li>",
    limit: 200
}

$('.fr-view').atwho(config);
```

**Comment by escopecz** [comment]
I get the same error with Froala 2.2.4:

`jquery.at.js:685 The given range isn't in document.`

at this line: https://github.com/ichord/At.js/blob/master/dist/js/jquery.atwho.js#L685

I'll try to downgrade to 1.2.8 as it seems to be working there, but a proper fix for the latest version would be great.

**Comment by luongm** [comment]
FYI, for anyone else getting this error, I followed the example on [froala website](https://www.froala.com/wysiwyg-editor/examples/at-js), but one difference I made which I thought was smart was instead of:
```
editor.events.on('keydown', function (e) {
   if (e.which == $.FroalaEditor.KEYCODE.ENTER && editor.$el.atwho('isSelecting')) {
      return false;
   }
}, true);
```
I moved this in the event listener of froala post initialization:
```
$('#froala-editor').on('froalaEditor.keydown', function(e, editor, keydownEvent) {
   if (e.which == $.FroalaEditor.KEYCODE.ENTER && editor.$el.atwho('isSelecting')) {
      return false;
   }
});
```
and that caused the error `The given range isn't in document`.

So just do exactly as in the tutorial and add the event listener in the `froalaEditor.initialized` handler and everything will work fine.

**Comment by gefangshuai** [comment]
@ichord don't work

**Comment by stefanneculai** [comment]
@gefangshuai see https://www.froala.com/wysiwyg-editor/examples/at-js.

**Comment by NathanDubord** [comment]
@stefanneculai I followed the Froala example and have atjs pretty much working, but there's issues with deleting inserted tags. I noticed the markup is slightly off from the example. This is the markup that's getting inserted:
`<span class="atwho-inserted" data-atwho-at-query="@" contenteditable="false">@Nathan</span>`

And this is the example site: 
`<span class="atwho-inserted" data-atwho-at-query="@">@Emma</span>`

Any idea why I'm getting contenteditable="false"?

My config:
```
let config = {
    at: '@',
    data: names,
    displayTpl: '<li>${name} <small>${email}</small></li>',
    limit: 100
};
```

**Comment by juliantabona** [comment]
I'm using summer note WYSIWYG editor, it seems to work and post fine but the trick is when i post the "Hi @julian" with no follow up text after the name or if i get post the name "@julian" alone it starts looking funny or the rendered post after the refresh. It only works when i put text on both sides of the name like "Hi @julian my friend". I noticed that when it fails it posts the query string
![sample]

![sample](https://user-images.githubusercontent.com/27730198/30403289-3c4add38-98e1-11e7-876a-00ebff863b39.jpg)

![sample 2](https://user-images.githubusercontent.com/27730198/30403513-46902dce-98e2-11e7-9677-7ee7e7b98fb6.jpg)

**Comment by chrisfay** [comment]
I am seeing the same behavior as @juliantabona. If I don't place text immediately after the match it doesn't insert, but leaves something like this behind that breaks it moving forward:

`<span data-fr-verified="true" class="atwho-query">@cfay</span>`

**Comment by feroj21** [comment]
@juliantabona @chrisfay Did you get any solution? I am having same problem.

**Comment by loutocky** [comment]
If you want to navigate inside variable, this works for me (froala + at.js)

```
private froalaInitializedEvent(atJsconfig: Object): Object {
    return function (e, editor) {
      editor.$el
        .atwho(atJsconfig)
          .on('inserted.atwho', function () {
            // we need to edit also text, which was added by autocomplete
            editor.$el.find('.atwho-inserted').removeAttr('contenteditable').removeAttr('data-atwho-at-query');
        })
   editor.events.on('keydown', function (e) {
        if (e.which == $.FroalaEditor.KEYCODE.ENTER && editor.$el.atwho('isSelecting')) {
          return false;
        }
      }, true);
    }
  }
```

**Comment by ghasemif** [comment]
@ichord 
I use at.js  with Froala Editor but after clearing the selected item , there is a error
"Cannot read property 'top' of undefined"
This bug is on the link below 
[https://jsfiddle.net/froala/wrc9mu3m/](url)
what should I do ?
