### ISSUE TITLE
Why does "tplEval" callback is called when it inserts to inputor?

### ISSUE THREAD

**Issue by VanDalkvist** [ichord/At.js#256]
Why is it should be? How can I configure template only for list view?

**Comment by ichord** [comment]
there is a `displayTpl` and `insertTpl`.
`tplEval` callback is like a template eval engine; it's for common cases. 
What situation make you want to just configure template only for list view?

**Comment by VanDalkvist** [comment]
I use AngularJS and I want to put angular directives to the ```displayTpl```. And I have to compile it, but I can't compile only ```displayTpl``` using this way. Also ```insertTpl``` I want to use to paste only direct value, because I use at.js for ```input["text"]```. So, I don't see any ways to do what I want

**Comment by ichord** [comment]
I think is a special case. 
I will pass the third argument , for example, 'onInsert'/'onDisplay', to `tplEval` callback. What do you think?

**Comment by VanDalkvist** [comment]
It would be helpful, thanks!
Also do you have any ways to get ListItem html element?
