### ISSUE TITLE
first atwho-inserted gets removed when selecting text using CTRL+A

### ISSUE THREAD

**Issue by vahtel** [ichord/At.js#258]
The first atwho-inserted tag gets removed when you select all the text using keyboard shortcut CTRL+A. 
It's broken when the line starts with the input but works if there is some text before the inputor.

Test case:
1. Type inputor "@user" to input box
2. Type some text
3. Type inputor "@user2" to input box
4. Press CTRL+a to select text

Result:
Text selecting fails, the first atwho-inserted tag is removed and cursor is placed before the second inputor
![select](https://cloud.githubusercontent.com/assets/396759/6556096/eacab8c6-c673-11e4-9d4f-f5c308ed2459.gif)

**Comment by ichord** [comment]
It's ok in my test case
![atjs](https://cloud.githubusercontent.com/assets/1324791/6801834/3975e7cc-d266-11e4-8303-d4efac5baa71.gif)

**Comment by ichord** [comment]
oh. CTRL + A is ok too.

![atjs](https://cloud.githubusercontent.com/assets/1324791/6801904/9843307a-d266-11e4-8636-91e259667061.gif)

**Comment by vahtel** [comment]
Start with a inputor, ex
 "@user asdasdasd @user"  - this is broken.
 "adasd @user adasd @user" - this works.

What browser did you try ? It's broken with Chrome,Safari on Mac and Chrome on Windows. Seems to work with Firefox and IE11.

**Comment by ichord** [comment]
oh.  It's a bug.

**Comment by houd1ni** [comment]
Couldn't repeat the bug. Is it fixed?

**Comment by ichord** [comment]
@houd1ni sorry, not yet.. It's might not easy to repeat but it does exists.

**Comment by houd1ni** [comment]
@ichord I probably will use it in my private message app. And, maybe, will contribute there too. Firstly,  removing issues :smile: Then, if you want, add 'nogithub' add-ons to be able use ":)" and so on.
I'll be grateful, if you help me to repeat.

**Comment by ichord** [comment]
@houd1ni  at the contenteditable input (second one) in http://ichord.github.io/At.js/

![at](https://cloud.githubusercontent.com/assets/1324791/7557287/1bf9e858-f7c1-11e4-9137-68af0ede13fb.gif)

**Comment by houd1ni** [comment]
@ichord thanx, got it!
