### ISSUE TITLE
Insert contenteditable=false element

### ISSUE THREAD

**Issue by loed-idzinga** [ichord/At.js#261]
Hi there!

Is there a way to force contenteditable='false' to the inserted span? Also would like to insert some data-attributes to this span, but when i'm editing the insertTpl, the span that i'm inserting gets wrapped by the at-who-inserted span, would like to change this behaviour so I can add the contenteditable=false and data-attributes.

**Comment by ichord** [comment]
There were lots of problem of `contenteditable=false` so that i had removed it.
But you can use `editableAtwhoQueryAttrs` options to hack it. ref: #253
