### ISSUE TITLE
Multiple replacement on the same line is deleting texte before cursor

### ISSUE THREAD

**Issue by MrHalfman** [ichord/At.js#262]
Hi, using contenteditable I have a bad behavior, see the image below : 

![Gif](http://g.recordit.co/DaF0a8IXtk.gif)

**Comment by ichord** [comment]
Sorry not to reply in time, for it's a difficulty bug and i don't have much time to fix it;
And i'm sorry to tell that i might wouldn't fix it if not much people get this bug, for it's hard to fix and not "usual"

**Comment by MrHalfman** [comment]
Oh okay :(.

Thanks for the answer and for the awesome work but that bug makes the library unusable with contenteditable, a pity because I really like your library.

**Comment by houd1ni** [comment]
Replacing things when edit closer than one space is looks like a feature, not bug :smile_cat:

**Comment by MrHalfman** [comment]
Sorry but I don't understand your comment @houd1ni :(

This bug can happen when you are many lines under a replaced content.

**Comment by houd1ni** [comment]
@MrHalfman I saw and then removed comment at once. Will think about that issue nearest time :wink:

**Comment by MrHalfman** [comment]
Thanks! :smile:

**Comment by houd1ni** [comment]
@MrHalfman done it. Wait for pull request and accept :smile:

**Comment by MrHalfman** [comment]
Many thanks to you :clap: @houd1ni !

**Comment by houd1ni** [comment]
@MrHalfman :wink: come here oftenly. Hope, Harold will too. I make own communication app and just don't want to propogate branches. Maybe, then I'll add some functions of earlier work for that app to merge it, if Harold agree, of cource :smiling_imp:

**Comment by ichord** [comment]
reopen for not solved perfectly.

**Comment by houd1ni** [comment]
What the problem of this solution?
Making insertions non-editable is the most native way, I thought.
By the way, demo is still old.
