### ISSUE TITLE
Multiple instances of At.js remote filter

### ISSUE THREAD

**Issue by loed-idzinga** [ichord/At.js#263]
Hi there! 

I'm using At.js for up to six trigger words (words as: mr, ms, etc.) but every time the first trigger word is triggered, the sixth remote filter is executed. It seems that only the last remote filter is executed. 

Is there an other way the retrieve sources from multiple ajax calls, which have different urls? Or could I extend the remote filter to match the subtext from the matcher?

Keep up the good work :+1: !

**Comment by ichord** [comment]
one `at` (trigger words) should match one remote filter. It work find in my try.
