### ISSUE TITLE
Feature request: reposition API method

### ISSUE THREAD

**Issue by adam-lynch** [ichord/At.js#264]
What I want is to basically force At.js to update it's position because the textfield has moved or the window has been resized. Not sure what to name it though.

**Comment by adam-lynch** [comment]
Calling `.atwho('run')` seems to do the trick for now but the first item becomes the current one (`.cur`) again and there seems to be a tiny bit of flicker (unless that's something to do with my app).

**Comment by ichord** [comment]
What about [reposition event](https://github.com/ichord/At.js/wiki/Events#repositionatwho)

**Comment by ichord** [comment]
And there is a `beforeReposition` callback in [callbacks](beforeReposition)

**Comment by adam-lynch** [comment]
But can I do `$('...').trigger('reposition.atwho')`?
