### ISSUE TITLE
Multiple listeners with remote filter don't work

### ISSUE THREAD

**Issue by jiin** [ichord/At.js#268]
Hi,

I'm using atwho to bind @ char and # char with a remote callback definedwith remoteFilter. But it seems to run only the latest one!  
```javascript
element.atwho({ at: '@', ... , callback: { remoteFilter: ... }});
element.atwho({ at: '#', ... , callback: { remoteFilter: ... }});
```
Any idea?

**Comment by krskrs** [comment]
Hi @ichord, in regards to this issue, please see my comment here: https://github.com/ichord/At.js/commit/bf938db68ab4c82f0ed885fec602241e38c49191

**Comment by ichord** [comment]
@jiin please show me the completed configuration. I have a try and it work fine.
