### ISSUE TITLE
Minified version of 1.10 replaces entire line upon selection.

### ISSUE THREAD

**Issue by austinwang** [ichord/At.js#269]
Steps to replicate...
include dependencies jquery, caret, atwho v1.10.

Only the minified version of v1.10 seems to be affected.

1. Type some stuff then at end of line, do '#' and select any option. It will work fine.
2. Press enter for new line. Repeat step 1. See that it replaces the entire line with the selected word

html
```html
<div contentEditable='true'>
```
and js
```javascript
$('div[contenteditable]').atwho({
    at: "#",
    data: ["budget", "timeline", "authority", "need", "painpoint"],
    insertTpl: '#${name}&nbsp;'
})
```

**Comment by ichord** [comment]
which browser?
I can't reappear this bug. It would be great to show me a demo on jsfiddle or others tool.

**Comment by austinwang** [comment]
Ah sorry, appears to be user error. :)
