### ISSUE TITLE
Why `getInsertedItemsWithIDs`, `getInsertedItems` and `getInsertedIDs` removed?

### ISSUE THREAD

**Issue by fengkaijia** [ichord/At.js#273]
Hi,

It's written in the Changelog of v0.5.0 that "Removing getInsertedItems, getInsertedIDs API. You have to collect them on your own.". Why were these great API removed?

**Comment by ichord** [comment]
I don't want to mix data in the inserted item and maybe the `data` is no `ID` column. 
I think it's better to let you do it on your own by configure the `insertTpl` option.
