### ISSUE TITLE
Using at:'@' with any keyboard character input?

### ISSUE THREAD

**Issue by signalarun** [ichord/At.js#274]

**Comment by TOuhrouche** [comment]
Have you checked the settings API? The first parameter is what you need to change to your needs

**Comment by signalarun** [comment]
Which API?

**Comment by signalarun** [comment]
You mean <at:> paramenter, I want the popup for all sequence of characters which I type.

**Comment by TOuhrouche** [comment]
If you want the popup to show when for example typing `a` you need to set:
`$('.atwho-inputor').atwho({
    // key char for observing such as `@`
    at: 'a',
});`

**Comment by signalarun** [comment]
Suggestion should appear for while typing words.eg. for ORANGE, this should be the sequence O,OR,ORA,ORAN, ORANG, ORANGE

**Comment by signalarun** [comment]
Issue soved, by setting at: to empty
