### ISSUE TITLE
Integration with medium-editor: Focus issues

### ISSUE THREAD

**Issue by NoelBaron** [ichord/At.js#275]
While using medium-editor: 

Once my TPL is pasted in by AT.JS, the editor loses focus and the user is unable to type until they manually click on the editor. I looked for a way to tie together focus events between plugins, but I was unsuccessful.

**Comment by ichord** [comment]
Sorry not replaying in time.  I tried on the newest version of medium-editor and couldn't reappear this bugs; it work fine in `examples/medium-editor.html` demo.

BTW. I can't reply in time recently and please give me as much information as possible; It's best to give me a example by jsfiddle or something else, thanks.
