### ISSUE TITLE
Only allow one @result by each sentence

### ISSUE THREAD

**Issue by DmonteiroD** [ichord/At.js#276]
With this basic example we can have multiples citations in the same sentence. 
Something like: @one @two hello!

Also, duplicated  names are allowed. This doesn't make sense.
@one @one hello!

``` 
$('#test').atwho({
    at: "@",
    data: ["one", "two", "three"]
});
``` 

Would be nice if there is an option to only allow one citation, or at least avoid duplications. In this case only allow:
@one hello! 

Basically something like stackoverflow in comments. This is currently possible? I didn't find any information about this in docs.

**Comment by ichord** [comment]
sorry that At.js wouldn't support it in textarea mode, but it's possible for contenteditable mode.

In contentable mode, you can save inserted item by marking them by the `insertTpl` [settings](https://github.com/ichord/At.js/wiki/Base-Document#settings) and filter the items by the `filter` [callbacks](https://github.com/ichord/At.js/wiki/Callbacks).
