### ISSUE TITLE
A way to trigger .show()

### ISSUE THREAD

**Issue by brihogan** [ichord/At.js#28]
Is there a way to trigger the `.show()` method manually? That is to say could I call something like `$('#inputor').atWho.show("@")` and get the drop down list? I can't figure out how to do something like this.

In other words, it'd be nice if there were a way to show the menu even if a user hasn't typed the appropriate flag. I have a situation where the `@` is added to the beginning automatically so that means the user never presses the trigger button - so I need a way to force the menu to open.

**Comment by ciriac** [comment]
@brihogan Did you manage to get this to work? I have the exact same use case for a project that I'm working on.

@ichord is the lookup method available or do I have to fork the project to expose this?

**Comment by yasir-rafiq** [comment]
Can you mention how we can use it?

**Comment by GMiLL5** [comment]
I also needed to do this in my project, I got around it by using the atwho object in the bound element's data:
`$el.data( 'atwho' ).controllers[ '@' ].view.show( )`
