### ISSUE TITLE
Uncaught Error: Method isSelecting does not exist on jQuery.caret

### ISSUE THREAD

**Issue by torifat** [ichord/At.js#289]
https://github.com/ichord/At.js/wiki/APIs#isselecting

https://github.com/ichord/At.js/blob/master/examples/tinyMCE.html#L26

**Comment by ichord** [comment]
please try on the `master` branch. I can't reappear this issue.
I will release a new version today.

**Comment by torifat** [comment]
@ichord Thank you very much. I have published the `Caret.js` in npm. I needed it badly for a production deployment. I have just added you as a contributor too. I can remove myself if you want. Thanks.

**Comment by ichord** [comment]
Doesn't matter, it's good.
