### ISSUE TITLE
"atwho-query" and "atwho-inserted" not encapsulating suffix

### ISSUE THREAD

**Issue by NSinopoli** [ichord/At.js#290]
Hi there, thanks for all of your great work with this library!

I've encountered an issue with the way suffixes are handled. The `span` elements that are generated do not include the suffix. Here's my code:

```coffee
$('#textarea')
  .atwho({
    at: '['
    data: [{ name: 'total', description: 'total amount' }]
    #insertTpl: '[${name}]'
    displayTpl: '''
      <li>
        <p><strong>[${name}]</strong></p>
        <p>${description}</p>
      </li>
    '''
    suffix: ']'
  })
```

### atwho-inserted

Steps to reproduce:

1. Type `[tot` in the textarea to see the menu come up.
2. Hit tab to choose `[total]`
3. Inspect the textarea element to view the markup:

`<span class="atwho-inserted">[total</span>]`

Note how the suffix is _outside_ the span element.

### atwho-query

Steps to reproduce:

1. Type `[total]` in the textarea.
2. Move the cursor so that it's between the `l` and the `]`. 
3. Hit backspace (deleting the `l`), and then re-type `l`.
4. Don't choose the element from the list.
5. Inspect the textarea element to view the markup:

`<span class="atwho-query">[total</span>]`

Again, note how the suffix is outside the span element.

What can I do to get the suffix inside the span elements? Thanks for any insight you can offer!

**Comment by ichord** [comment]
oh... suffix will be inserted outside the wrapper. It's should be inserted inside; but a space must be inserted outside and after the wrapper.

**Comment by NSinopoli** [comment]
@ichord Thanks so much for tackling this!

The `atwho-inserted` issue I described above is fixed with your patch, but the `atwho-query` issue remains.

**Comment by ichord** [comment]
I notice that you had tryed to use this:  `insertTpl: '[${name}]'` , didn't it work for you?
`suffix` is for outside of the block, or it's conflict with the `insertTpl`.

**Comment by ichord** [comment]
BTW. thanks for your detailed description.

**Comment by NSinopoli** [comment]
Unfortunately, no. Even when I use `insertTpl`, I still have the same issue with the `atwho-query` span element.

```coffeescript
$('#textarea')
  .atwho({
    at: '['
    data: [{ name: 'total', description: 'total amount' }]
    insertTpl: '[${name}]'
    displayTpl: '''
      <li>
        <p><strong>[${name}]</strong></p>
        <p>${description}</p>
      </li>
    '''
  })
```

### atwho-query

Steps to reproduce:

1. Type `[total]` in the textarea.
2. Move the cursor so that it's between the `l` and the `]`. 
3. Hit backspace (deleting the `l`), and then re-type `l`.
4. Don't choose the element from the list.
5. Inspect the textarea element to view the markup:

`<span class="atwho-query">[total</span>]`

The final character `]` is still outside the span.

This was tested with the latest version of At.js.

**Comment by ichord** [comment]
oh.... you typed the whole `[total]` without using At.js to complete it...
And the `matcher` can't match the `[` so that At.js would start to search.
For now, you have to override the `match` callback to solve the problem if you really think it's a big problem.

**Comment by NSinopoli** [comment]
The `matcher` callback won't fire when reproducing the `atwho-query` issue described above.

In the event someone reads this in the future, here's what I did. (Note that this assumes you have jQuery and underscore/lodash.)

```coffee
stripTags = (text, selectors) ->
  wrapped = $("<div>#{text}</div>")
  _.each selectors, (selector) ->
    wrapped.find(selector).contents().unwrap()
  wrapped.html()

stripTags 'YourTextHere', ['.atwho-query', '.atwho-inserted']
```

**Comment by ichord** [comment]
The `matcher` callback will be called every times the text area is changed; It should be fired if there is no exception.
As I mentioned above, You can override the `matcher` to solve this problem. This is the regexp work on my try:

```coffeescript
regexp = new RegExp "#{flag}([A-Za-z#{_a}-#{_y}0-9\\]_#{space}\.\+\-]*)$|#{flag}([^\\x00-\\xff]*)$",'gi'
```

here is the whole `matcher` callback (Sorry it's bad to override it to just change the regexp):

```coffeescript
  matcher: (flag, subtext, should_startWithSpace, acceptSpaceBar) ->
    # escape RegExp
    flag = flag.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&")
    flag = '(?:^|\\s)' + flag if should_startWithSpace

    # À
    _a = decodeURI("%C3%80")
    # ÿ
    _y = decodeURI("%C3%BF")
    space = if acceptSpaceBar then "\ " else ""
    regexp = new RegExp "#{flag}([A-Za-z#{_a}-#{_y}0-9\\]_#{space}\.\+\-]*)$|#{flag}([^\\x00-\\xff]*)$",'gi'
    match = regexp.exec subtext
    if match then match[2] || match[1] else null
```
