### ISSUE TITLE
at-who div not scrolling with window (again)

### ISSUE THREAD

**Issue by celluj34** [ichord/At.js#292]
Hello! I'm still having an issue with the at-who list moving when scrolling the window, or when the window scrolls itself (chat application). I did read about #166, and that it was fixed, but I'm still seeing this issue with the latest of at.js. Please see attached image:

This one is correct: http://i.imgur.com/VPDFW4P.png
This one shows what happens after the window scrolls a bit: http://i.imgur.com/FojpJpt.png

Note, I am using an input element, not a div or textarea.

**Comment by ichord** [comment]
hmmm... I forgot how it's fixed.
But now you can listen to the window's `scroll` or `resize` event and call the `reposition` api to reposition the view:

```coffeescript
$textField.atwho('@', 'reposition')
```

**Comment by celluj34** [comment]
Thanks! It's working great now. Though the code you provided doesn't work, I did find that removing the '@' does, like so:

    $textField.atwho('reposition')

One more small thing. Every time I reposition the window using this code, it writes to the console. Is there a setting I can set to make it not do that? It's not a big deal, but I'd like to keep the console clean.

**Comment by ichord** [comment]
I removed it in v1.3.0 , sorry about that.
