### ISSUE TITLE
acceptSpaceBar param is missing

### ISSUE THREAD

**Issue by ceritium** [ichord/At.js#293]
[matcher](https://github.com/ichord/At.js/blob/015530991f8dbc881c210ed86b1ab8655b1e03bd/src/default.coffee#L48) accept `acceptSpaceBar` as param.

Could you add the option in [catchQuery](https://github.com/ichord/At.js/blob/64ab00d4b86f12b2860963fd99aa91677419ee0f/src/textareaController.coffee#L9)?

**Comment by ichord** [comment]
that is the `startWithSpace` options, you could just get it by calling `@getOpt('startWithSpace')`.
And the `matcher` is called in the `catchQuery` function...
