### ISSUE TITLE
Suffix always inserts a space

### ISSUE THREAD

**Issue by RobertDiebels** [ichord/At.js#294]
Hi,

First of all, thank you for this amazing library. It's really useful!

We are trying to get your library to accept an empty value as a suffix. As we do not want a space to be inserted after a template.
However this bit of code `suffix = (suffix = this.getOpt('suffix')) ? suffix : suffix || "\u00A0";` always inserts a space even if we specifically say that we want an empty string "". This is treated as a false value in this bit of code and will always insert a nbsp.

Is there a possibility to fix this?

(Note: In the textarea controller you do check for "" with this piece of code `suffix = (suffix = this.getOpt('suffix')) === "" ? suffix : suffix || " ";`, I would extract a method an make that handle the suffix, so that both a text area and a content-editable handle this the same way).

**Comment by RobertDiebels** [comment]
Thanks for the fix! Much appreciated!

**Comment by fritx** [comment]
Having some trouble displaying `\u200D` on iOS.
My solution is to remove it from `createTextNode` in my forked code.

```js
// ...
EditableController.prototype.insert = function(content, $li) {
  // ...
      range.collapse(false);

+     // fix: \u200D cannot display on iOS
-     range.insertNode(suffixNode = this.app.document.createTextNode("\u200D" + suffix));
+     range.insertNode(suffixNode = this.app.document.createTextNode(suffix));

      this._setRange('after', suffixNode, range);
}
```

Ref: https://github.com/ichord/At.js/issues/411#issuecomment-256662090
