### ISSUE TITLE
The cursor goes always at start of textarea

### ISSUE THREAD

**Issue by xillibit** [ichord/At.js#309]
I'am using at.js 1.3.2 with jQuery 1.11.2, jQuery-migrate 1.2.1 and bootstrap 2.3.2, each time i'am typing into the textarea the cursor goes alway at start of textarea.

I'am on firefox 38.0.5

Even with your example code it does the same : 

```js
var emojis = ["smile", "iphone", "girl", "smiley", "heart", "kiss", "copyright", "coffee"];
var emojisList = jQuery.map(emojis, function(value, i) {
  return {'id':i, 'name':value};
});
//http://a248.e.akamai.net/assets.github.com/images/icons/emoji/8.png
jQuery(item).atwho({
  at: ':',
  displayTpl: "<li><img src='http://a248.e.akamai.net/assets.github.com/images/icons/emoji/${name}.png' height='20' width='20'/> ${name} </li>",
  insertTpl: ":${name}:",
  data: emojisList
});
```
With the version 0.4.12 i don't have this issue, but i wanted to migrate at.js to 1.3.2

Do-you have an idea to make it working correctly ?

**Comment by dryabchenko** [comment]
I have the same bug. Google Chrome 44.0.2403.125

**Comment by xillibit** [comment]
Any news on it ?

**Comment by xillibit** [comment]
Do-you have news on it ? I'am still experencing the issue with firefox 41.0.1

**Comment by xillibit** [comment]
I'am closing this one because i'am not encounter this issue anymore

**Comment by karser** [comment]
I started getting this error recently, I tried at.who 1.4.0, 1.5.1, 1.5.2, 1.5.3.
Not sure what causes this problem.
Here is my jquery version:
```
    "jquery": "3.1.1",
    "jquery-migrate": "3.0.0",
```
