### ISSUE TITLE
how to insert a mention programmatically

### ISSUE THREAD

**Issue by javenwang** [ichord/At.js#311]
Hi, I have a button and a textarea and I want to insert a mention when I click the button. I tried something like this:
```
$('#text').data('atwho').controller('@').insert('someone');
```
but got an error:
```
Uncaught TypeError: Cannot read property 'el' of null
EditableController.insert @ jquery.atwho.js:688
```
Any suggestion?

**Comment by ichord** [comment]
When you click on a button, textarea will trigger a `blur` event, it will interrupt At.js's running context.
There is no way to do that as i know.
