### ISSUE TITLE
contenteditable cursor bug when typing "a" into query 

### ISSUE THREAD

**Issue by vincentschen** [ichord/At.js#312]
Cursor returns to the beginning of the tag (in this case, "##") when 'a' is typed in the query.

![atjs-2](https://cloud.githubusercontent.com/assets/5819303/8626460/d16c538a-26f9-11e5-86f9-0ff6efa2d2df.gif)

**Comment by riaandewit** [comment]
@vincentschen - did you find a solution? I am facing the same kind of problem :(

**Comment by vincentschen** [comment]
@riaandewit unfortunately, not for this library! I liked the ability of at.js to use any tag to trigger autocomplete, but ended up modifying another library to do so.

**Comment by riaandewit** [comment]
... I may have found a workaround: In the configuration section, the KEY_CODE object is defined with A:65 - so the system is listening for a press of the "a" key. There's some checking whether CTRL is also pressed, and some stuff done based on that. Some interaction with this code is causing it to freak out. I just changed A:65 to A:999 - bypassing CTRL-A functionality, and preliminary testing looks like it's working for my desired case. Hope this helps, people.

**Comment by ichord** [comment]
cased by #258
