### ISSUE TITLE
Publish this library to a CDN

### ISSUE THREAD

**Issue by hajekj** [ichord/At.js#317]
Hello, it would be very beneficial for me, and definitely for other projects as well if you published this library on [CDNJS](https://cdnjs.com) or some similar CDN service, so we wouldn't have to host the content locally. It would also help with version management and so on.
Thanks for considering this.

**Comment by ichord** [comment]
How about this one: http://www.jsdelivr.com/

**Comment by hajekj** [comment]
Oh, totally missed that. Thanks a lot!

**Comment by Mottie** [comment]
Hi @ichord!

Any chance you could update the version at jsdelivr? It's currently providing v0.5.0.

Thanks!
