### ISSUE TITLE
get attribute value of an json object attribute

### ISSUE THREAD

**Issue by leizard** [ichord/At.js#320]
with a json object like this:
```
user: {
  "_id": "y46f32uLDvgMxKjpe",
  "username": "jack",
  "profile": {
       "username": "jack",
  }
}
```

it works if I use "${username}" to get the username of the user. But I can't use "${profile.username}" to get the username property inside the profile property. Where was I wrong ?
Thank you.

**Comment by ichord** [comment]
You can use `tplEval` callback to evaluate the tpl on your own.
https://github.com/ichord/At.js/wiki/Callbacks
