### ISSUE TITLE
Change key to trigger select

### ISSUE THREAD

**Issue by JosephHier** [ichord/At.js#323]
Is there any way to change what key triggers an item selection? For example, I want an item to be selected when the user hits the spacebar, not the enter key.

**Comment by DDaems** [comment]
This option allready exists, change 'false' to 'true'
https://github.com/ichord/At.js/blob/master/dist/js/jquery.atwho.js#L1126

Or you can change it directly in the source and compile your own version. Change 'no' to 'yes' here
https://github.com/ichord/At.js/blob/master/src/api.coffee#L48

**Comment by ichord** [comment]
Sorry, the key is not configurable.
