### ISSUE TITLE
HTML is not sanitized in displayTpl

### ISSUE THREAD

**Issue by styfle** [ichord/At.js#334]
The `displayTpl` should escape properties before rendering. This could lead to XSS attack. Example of the problem:

```js
var data = [
    { name: "<<Unassigned>>", alias: "Unassigned" }, // bug here
    { name: "Steven", alias: "styfle" },
    { name: "Harold", alias: "ichord" },
    { name: "<script>alert('hacked!')</script>", alias: "hacked" } // malicious bug here
];

$("#mytextarea").atwho({
    at: "@",
    displayTpl: '<li>${name} <small>${alias}</small></li>',
    insertTpl: "${atwho-at}${alias}",
    data: data,
    searchKey: 'name'
});
```

Now when you type the "@" symbol you'll get a "hacked" alert prompt!

**Comment by ichord** [comment]
please give At.js the sanitized data.

**Comment by styfle** [comment]
@ichord Is this documented anywhere? It seems like many users will not think of this and open a security hole.

Is there a way to use a function instead of a string? For example:

```js
$("#mytextarea").atwho({
    at: "@",
    displayFn: function(item) {
        return '<li>' + sanitize(item.name) + ' <small>' + sanitize(item.alias) + '</small></li>';
    }
    insertTpl: "${atwho-at}${alias}",
    data: data,
    searchKey: 'name'
});
```

**Comment by ichord** [comment]
At.js use `tplEval` to evaluate `insertTpl` and `displayTpl`, and it accept both function and string. You can do the sanitize there. Hmm, Sorry that i didn't documented it yet. 
here the related commit #259

**Comment by styfle** [comment]
@ichord Thanks that looks like it works!
```js
$("#mytextarea").atwho({
    at: "@",
    displayTpl: function(item) {
        return '<li>' + sanitize(item.name) + ' <small>' + sanitize(item.alias) + '</small></li>';
    },
    insertTpl: "${atwho-at}${alias}",
    data: data,
    searchKey: 'name'
});
```

I updated the wiki. I'm also working on writing a `.d.ts` file with the proper types. See [this gist](https://gist.github.com/styfle/769f1e9ba5ce4f6468a7) for more.
