### ISSUE TITLE
[Questions] Adding an image to the drop down and altering the output once a name is selected

### ISSUE THREAD

**Issue by deronsizemore** [ichord/At.js#336]
Just curious if this is possible? I tried searching but didn't come up with anything in the issues area and didn't feel like manually browsing through all the closed tickets.

I just want to add a users profile image to the drop down as well as changing the @mention to a link once the name is selected.

Here's a working fiddle of the code and the editor I'm using: http://jsfiddle.net/2rh7vzg3/

**Comment by ichord** [comment]
`[insertTpl](https://github.com/ichord/At.js/wiki/Base-Document#settings)` is for inserting, you can alter the inserting content by it. I update the jsfiddle, check out if it's what you need:
http://jsfiddle.net/2rh7vzg3/1/

**Comment by deronsizemore** [comment]
@ichord Thank you. That's what I needed in regards to inserting a link.

I actually found out how to insert the profile image into the mention here: https://github.com/ichord/At.js/wiki/Base-Document#custom-template

My question now becomes about how to use the data I'm returning via json? (sorry I'm a js novice).

For example, I'm using Django and returning the json data below with my current mentions plugin (not at.js):

    'value': '%s' % (item.user.username),
    'image': image,
    'id': '%s:%s' % (item.user.username, item.id),

The above code returned in json format:

    [{"image": "https://amazonaws.com/uploads/mugshots/d6ad2da421.jpg", "id": "deronsizemore:18", "value": "deronsizemore"}, {"image": "/assets/images/silhouette.png", "id": "deronfake:143", "value": "deronfake"}]

So I assume I'd have to map that data with this?

    var names = $.map(datasource, function (value, i) {
        return {
            'id': i, 'name': value, 'email': value + "@email.com"
        };
    });

I guess my question is how to pass the image value into that? I see above you pass "value" and "i." So would I need to pass one more for my profile "image?"

Maybe?

    var names = $.map(datasource, function (value, i, image) {
        return {
            'id': i, 'name': value, 'image': image
        };
    });

Also, sorry I forgot to ask this initially, but what about only showing the drop down after the user starts typing a name instead of showing a dropdown of names as soon as the user types the @ sign? With the current mentions app that I use, the url is given a query parameter e.g.: 

    http://example.com/mentions?term=Foo

so then my code on the backend I just query users that start with "Foo" and return them as json. Is something like that possible with At.js?

Thanks again!

**Comment by ichord** [comment]
About the tpl:
Yes, you are right.
At.js will evaluate the `key` of the json data.
```javascript
displayTpl: "<img src='${image}' /> ${name}", // => <img src="https://amazonaws.com/uploads/mugshots/d6ad2da421.jpg" /> deronsizemore
insertTpl: "<a href='www.google.com/q?=${name}>Google ${name}</a>"
````

About the querying:
Don't pass anything to the `data` setting, and add a `remoteFilter` to the `callbacks` setting. It will be invoked every times if there is no `data`. Here is [example](https://github.com/ichord/At.js/wiki/How-to-use-remoteFilter)

**Comment by deronsizemore** [comment]
>About the tpl:
>Yes, you are right.
>At.js will evaluate the key of the json data

I'm sorry, but I'm not sure I follow what I was right about regarding tpl in my above comment? Was it how to map the data, e.g.,

    var names = $.map(datasource, function (value, i, image) {
       return {
            'id': i, 'name': value, 'image': image
        };
    });

Is that what was correct?

so I can pass "image" into the .map function? 

Regarding the data I'm passing via json: 

    [{"image": "https://amazonaws.com/uploads/mugshots/d6ad2da421.jpg", "id": "deronsizemore:18", "value": "deronsizemore"}, {"image": "/assets/images/silhouette.png", "id": "deronfake:143", "value": "deronfake"}]

I'm using "image," "value," and "id." So would I need:

    var names = $.map(datasource, function (value, i, image) {

or would I need:

    var names = $.map(datasource, function (value, id, image) {

Sorry, hope that makes sense? I'm sure it's easier than I'm making it out to be.

>Don't pass anything to the data setting, and add a remoteFilter to the callbacks setting. It will be invoked every times if there is no data. Here is example

Thanks, I think that makes sense. I'll give it a try and see what happens.

**Comment by deronsizemore** [comment]
Ok, sorry for all of my questions. I actually got this working today for the most part but still running into a  couple small problems.

Here's my current code which I was able to pull data from a remote datasource:

		var config = {
		    at: "@",
			callbacks: {
				remoteFilter: function(query, callback) {
				  $.getJSON("http://{{ request.get_host }}/mentions/", {q: query}, function(data) {
				    callback(data)
				    console.log(query)
				    console.log(data)
				  });
				}
			},
		    editableAtwhoQueryAttrs: {
		        "data-fr-verified": true
		    },
		    displayTpl: "<li><img src='${image}' height='20' width='20'/> ${value} </li>",
		    insertTpl: "<a href='http://www.golfledger.com/${value}'>@${value}</a>",
		}

You can see where I have     console.log(query) and     console.log(data) to try to figure out what's going on behind the scenes. Here is a screenshot of what I'm seeing in console: http://i.imgur.com/pk0eM2e.png

The problems:

1. If I start typing "deronsizemore" once I get to the "r" the dropdown goes away. It's fine on "d" and "e" but after "r" the dropdown disappears. It works great with a local datasource, but with the remote datasource, what I outlined above happens.

2. Still, as soon as I type the "@" sign, I get a drop down (of remote data). I don't want any remote data to show until the user starts typing their query. Can you confirm if the code above should be working that way or if I'm doing something wrong?

**Comment by ichord** [comment]
Try this. 
At.js will search the `name` key in data source by default, if you want it to search another key such as `value` in your data, you have to set `seachKey` to `value` .

**Comment by deronsizemore** [comment]
@ichord Ahhh... sorry, I'm an idiot. That makes perfect sense now.

I was also able to get the drop down to ONLY show after someone typed a letter. I did all that with some python code (I use Django). I'll post it below for someone who may find this later and have interest:

    def mentions(request):
	mention_data = []

	query = request.GET['q']
	if query:
		data = MyProfile.objects.filter(user__username__istartswith=query)[:5]

		for item in data:
			if item.mugshot:
				image = item.mugshot.url.split('?')[0]
			else:
				image = settings.USERENA_MUGSHOT_DEFAULT
			mention_data.append({
				'name': '%s' % (item.user.username),
				'image': image,
			})

	return HttpResponse(json.dumps(mention_data), content_type='application/json')

Thanks for all of your help on this.

**Comment by mazeeblanke** [comment]
hello, please how can i add a link using a normal textarea ?
