### ISSUE TITLE
IE, Edge, Chrome, minLen leads caret position goes to beginning

### ISSUE THREAD

**Issue by kkarahainko** [ichord/At.js#340]
Hello there,

http://jsfiddle.net/4hkbvx0z/1/

When minLen is defined, caret position goes to beginning all the time. Seems like minLen works fine only in Firefox.

JSFiddle attached, please look at video:

https://www.dropbox.com/s/0c8ojcmvtlfly64/bandicam%202015-08-31%2014-41-08-440.mp4?dl=0

Thanks.

**Comment by ichord** [comment]
It's fixed in master (going to release v1.5.0)
