### ISSUE TITLE
[bug] Problem adding period to the end of mention

### ISSUE THREAD

**Issue by deronsizemore** [ichord/At.js#342]
I'm inserting an anchor after the user selects an item from the list:

    insertTpl: "<a href='http://www.domain.com/${name}'>@${name}</a>",

I just noticed that if I insert an @mention and then hit backspace so that I can add a period to the end (this would be for cases when the mention was the last word in the sentence and I needed a period to close the sentence) that after the period is inserted, the anchor from the mention is removed from the source and thus the mention is no longer a link at that time.

Is this a bug with how I'm adding an anchor in the code? Can it be fixed somehow?

Thanks

**Comment by JeanCarriere** [comment]
+1

**Comment by ssshake** [comment]
+1

**Comment by ichord** [comment]
close for duplicated with #346
