### ISSUE TITLE
Optgroup-like behaviour?

### ISSUE THREAD

**Issue by enderteszla** [ichord/At.js#343]
My task at the moment is to implement a 'mention user' mechanism for our service to allow our users to mention each other in comments. 

At.js fitted perfectly. But there is one issue that has to be addressed in the nearest future: grouping elements of the drop-down list like Chosen allows us to. By now I've tried the following: I insert group label tag (the same li tag with a different class) in the first element of each group:

var at_config = {
...,
displayTpl: '&lt;li class="optgroup"&gt;${groupname}&lt;/li&gt;&lt;li class="option"&gt;${name} &lt;small&gt;${email}&lt;/small&gt;&lt;/li&gt;',
...
};

, where <i>groupname</i> is set to be not null only for the first element in each group.
However, this leads to an unpleasant (though, not unexpected) behaviour: click on the group label tag is treated as if user chose the first element from that group.

How'd you advise me to address this issue not having to modify much At.js code?

**Comment by ichord** [comment]
Sorry, wouldn't support. At.js is for search and autocomplete, there should be a few elements in the view. So At.js just want to provide a very simple view.
