### ISSUE TITLE
Does it support dynamic data source?

### ISSUE THREAD

**Issue by kxxoling** [ichord/At.js#347]
I'm try to find implement a AtWho function for my site just the same as GitHub. I need to get the result when the letter after ``@`` changes.

eg. I need to query the database for users having username like ``kx*`` when I inputed ``@kx``.

Is this supported? I can not find out how to implement it.

**Comment by laurentiustroia** [comment]
Yes, you should use remoteFilter callback and configure source to be null. Take a look here https://github.com/ichord/At.js/wiki/Callbacks

**Comment by kxxoling** [comment]
@laurentiustroia Thanks, I wrote something like this:

```js
$el.atwho({
      at: "@",
      tpl: "<li>${username}</li>",
      data: null,
      callback:{
        remoteFilter: function(query, callback){
          $.ajax('/api/user/autocompletion/'+query, {
            type: "GET",
            dataType: "json"
          }).done(function(data){
            console.log(data);
            callback(data);
          });
        }
      }
    });
```

But no error and no ajax request generated. Am I using it wrong?

**Comment by kxxoling** [comment]
Almost finished:

```js
    $el.atwho({
      at: "@",
      displayTpl: '<li>${username} - ${name}</li>',
      insertTpl: '@${username}',
      data: null,
      callbacks: {
        remoteFilter: function(query, callback){
          $.getJSON('/api/user/autocompletion/'+query, function(data){
            console.log(data);
            callback(data);
          });
        }
      }
    });
```

When I type ``@k`` I can get a list like ``kxxoling - Kane`` just as I expected. But when I type a more letter ``x``, the searching key becomes ``@kx``, and the backend returns the same data ('cause I have only one user), the list disappeared!

**Comment by kxxoling** [comment]
I found out what's wrong now. I forget to override the value of ``searchKey`` as the JSON returned looks like ``[{"name": "Kane", "username": "kxxoling"}].

Now everything works! Thanks very much! @laurentiustroia
