### ISSUE TITLE
Multiple searchKeys would be nice

### ISSUE THREAD

**Issue by adam-lynch** [ichord/At.js#349]
So then it would be easy to autocomplete like GitHub do here in their issues. You can write a part of someone's full name (not in their username) and it'll be matched.

**Comment by adam-lynch** [comment]
Ok, so I managed this. For anyone looking to do this, you need to override the filter and sorter callbacks. In your filter callback, call `$.fn.atwho.default.callbacks.filter` *twice*. Both times pass the `query` and `data` you're passed as arguments but pass different values in each case for the `searchKey` (e.g. `username` and `name`). Then merge the results from both calls, remove duplicates (but you might want to keep track of which call(s) it was returned from, to help with sorting later). Then your sorter will have to sort these. You must give a sorter callback or it won't work, even if it only returns the `items` its given, but you probably want to place matches matched against one `searchKey` higher than another.

The only problem left to solve now for me is getting the highlighting to work (related: #350).

**Comment by ichord** [comment]
You can just combine what you want to search into a key, such as `searchContent`, and set it as `searchKey`?

**Comment by adam-lynch** [comment]
I don't get ya

**Comment by ichord** [comment]
```javascript
{
  at: "@",
  data: {"firstName": "Michael",  "lastName": "Nickle", "search": "Michael Nickle"},
  searchKey: "search"
}
```

**Comment by adam-lynch** [comment]
I want to be able to search two unrelated things. This doesn't really work
for that.

**Comment by ichord** [comment]
Wouldn't implement it, for I want to keep it simple and stable for now. sorry.

**Comment by vick-subbu** [comment]
> ```js
> {
>   at: "@",
>   data: {"firstName": "Michael",  "lastName": "Nickle", "search": "Michael Nickle"},
>   searchKey: "search"
> }
> ```

This will not work if your searchString has space, 
For Eg: If someone types "Michael", then hit space, this would break

**Comment by Octobug** [comment]
> > ```js
> > {
> >   at: "@",
> >   data: {"firstName": "Michael",  "lastName": "Nickle", "search": "Michael Nickle"},
> >   searchKey: "search"
> > }
> > ```
> 
> This will not work if your searchString has space,
> For Eg: If someone types "Michael", then hit space, this would break

You can use the `matcher` callback to process user's input. Like, trims "Michael " to "Michael" in your case.

https://github.com/ichord/At.js/wiki/Callbacks

```JavaScript
# It would be called to match the `flag`.
  # It will match at start of line or after whitespace
  #
  # @param flag [String] current `flag` ("@", etc)
  # @param subtext [String] Text from start to current caret position.
  #
  # @return [String | null] Matched result.
  matcher: (flag, subtext, should_startWithSpace, acceptSpaceBar)
```

@vick-subbu

**Comment by fglueck** [comment]
I have the same Problem, I use it für User selection. I have the name  xyyyyy and a description xxxxx yyyyyy. If I create a extra search field with both I have more then the double data in the json object and it is only neaded for searching in two values.

searchKey: ['name', 'otherfield']

should be a nice feature for that case
