### ISSUE TITLE
Changing wiki for beforeInsert

### ISSUE THREAD

**Issue by RobertDiebels** [ichord/At.js#353]
Hey guys,

This isn't an issue about the code but about the Wiki. I was looking at the callbacks page. More specifically at the "beforeInsert" documentation.

I tried altering my code to fit the spec given there to no avail. Only after I tried to actually return the string value did it start to work.

The wiki does not state that there should be a string value to return in the beforeInsert.

I'm going to go ahead and change the wiki (if I'm allowed). If this does not suit your wishes please remove my alteration.

Greetings, Robert.

**Comment by ichord** [comment]
just do it.
