### ISSUE TITLE
Is it still possible to place the template inside a parent element?

### ISSUE THREAD

**Issue by JordyPouw** [ichord/At.js#355]
I'm working on a project that used and older version. In the older version you had settings to define a parent element where the callback data would be placed inside. With the update to this version, it doesn't work anymore.

Is the old setting 'parent_el' removed or replaced by something else?

Thnx in advance!

**Comment by ichord** [comment]
please tell me which version and which setting.

**Comment by JordyPouw** [comment]
Sorry for the late reply, already fixed it. Thanks anyway!
