### ISSUE TITLE
How to select atwho-container related to specific textarea/atwho instance

### ISSUE THREAD

**Issue by bakaat** [ichord/At.js#360]
Hi,

We're using atwho for multiple textareas. Is it possible to select the atwho container related to the specific  textarea ? 
Or is there an option to specify the parent element where containers will be created (instead of being created directly in the `<body>` ?

cheers
Lukasz

**Comment by ichord** [comment]
sorry, no. 
Why you want to do that?

**Comment by bakaat** [comment]
Sorry @ichord, I must have missed your response.

As said we have multiple textareas. For each textarea we have 2 autocompleters.
We have 2 issues:

- when we create a new atwho instance for a new textarea a new atwho-container is created (instead of reusing an existing one ?).
- we need to reposition/resize the atwho result list after it's displayed, it would be nice to be able to just say `$field.atwho('getAtwhoGround')` and work with it.

**Comment by ichord** [comment]
oh, I found that you can get the `container` in this way:
`$('textarea').first().data('atwho').$el``

the `app` instance is store in element's data attribute

**Comment by bakaat** [comment]
Class Harold :D cheers !
