### ISSUE TITLE
中文匹配问题，及使用一次自动过滤

### ISSUE THREAD

**Issue by ouewqa** [ichord/At.js#362]
使用最简单配置。

输入@后，会有提示列表出来。有：`abc`, `中国人`,`123`

这时，如果我再输入一个字符`a`，这时列表就消失，按理要过滤掉`中国人`，并高亮显示`abc`中`a`才是。
需要怎么配置才能使用这个功能？（需要支持中文，如输入`中`，应过滤掉`abc`）

还有一个问题，比如在文本框中，我已经选择了 `@abc` 后，再次输入`@`,提示列表应过滤掉`abc`

这两个问题琢磨好久没弄懂。

`callbacks`中的`matcher`能详细说明一下么？

**Comment by ichord** [comment]
第一个问题，我试了下没有异常；那个消失应改是以为中文输入法的原因，在没有完全输入完毕时时不会去搜索的。

第二个问题，数据的处理方式要你们自己处理，At.js 只负责搜索，展示。不对数据做额外操作。

`match` wiki 里有说明，At.js 会把整个输入框中的文本从开头到光标的字符串传给 `matcher` ，`matcher` 返回匹配的字符串，比如输入 `@abc` ，返回 `abc` 。
