### ISSUE TITLE
Strange character in chrome with contenteditable

### ISSUE THREAD

**Issue by waqasss** [ichord/At.js#365]
![Iextra](http://i.imgur.com/r1LFgYn.jpg)

I'm getting an unwanted character in chrome using with contenteditable div. And it happens in your demo too.

**Comment by ichord** [comment]
Are you using version v1.4.1 ?

**Comment by waqasss** [comment]
v1.4.0 actually. Downloaded from [demo site] (http://ichord.github.io/At.js/dist/js/jquery.atwho.js)

**Comment by ichord** [comment]
and it's ok now?

**Comment by waqasss** [comment]
Hey, thanks for following up. It appears the problem is with chrome only. I can't seems to find v1.4.1 in repository either. I've switched to other available solutions
