### ISSUE TITLE
Why not using smaller version of javascript for caret position.

### ISSUE THREAD

**Issue by waqasss** [ichord/At.js#366]
Hello, I notice that jquery-caret.js is quite a large file. 12kb uncompressed. While another [caret position checker] (https://sandglaz.github.io/bootstrap-tagautocomplete/deps/caret-position.js) is just 2.60kb uncompressed. Can we use it instead?

**Comment by ichord** [comment]
That is just for `contenteditable`, but what about `textarea` ?
And there are some compatibility jobs have to be done.
If you would like to read the code, please checkout [Caret.js](http://ichord.github.io/Caret.js/) .

**Comment by ichord** [comment]
or maybe you can include caret position and write a shim to match the API; for example, `$('#input').caret('pos', 12')`
