### ISSUE TITLE
Smileys missing

### ISSUE THREAD

**Issue by TukuTuru** [ichord/At.js#367]
Somehow we don't have permission to your smileys library CDN

Do I miss something

Smileys only appearing after save, but not in list.

This is the code for list:
`.atwho({
    at: ":", 
    dispayTpl: "<li><img src='http://a248.e.akamai.net/assets.github.com/images/icons/emoji/${name}.png' height='20' width='20'/> ${name} </li>",
    insertTpl: ':${name}:',
    data: emojisList,
  limit: 10`

**Comment by ichord** [comment]
Please use your own, that is just for demo.
