### ISSUE TITLE
Question about searchKey and callbacks.remoteFilter options

### ISSUE THREAD

**Issue by ino-shin** [ichord/At.js#368]
Hi. I'm using remoteFilter feature of At.js for autocompleting img tags.
I want to filter images by ajax query in remoteFilter function only once, but data again filtered by searchKey property after remoteFilter called.
Is it specification? or bug? I think, when we use callbacks option, searchKey filter should be invalid.

**Comment by ino-shin** [comment]
Add sample code.

https://github.com/ino-shin/At.js/blob/issue_368/index_test.html

**Comment by ichord** [comment]
`searchKey` is used to match, filter and sort the value. The return data must match that data structure.
If not how can At.js know which is the value is? If there is only one value of the data, just return an array such as `["value one", "value two"]`.

At.js will always call the `remoteFilter` if `data` setting is empty.
