### ISSUE TITLE
Uncaught TypeError: this.$inputor.caret is not a function

### ISSUE THREAD

**Issue by Serhioromano** [ichord/At.js#369]
I have just installed it via bower. 

Here is my JS snippet. 

```js
$("#field_10").atwho({
	at: '@',
	limit: 10,
	data: 'get_users.php',
	dispayTpl: "<li>${name} <small>${username}</small></li>",
	insertTpl: ':${name}:'
});
```
Here is what is returned by URL

```json
[
    {"name":"Super User","username":"Sergey"},
    {"name":"Jon","username":"Jon Doe"}
]
```

And this is what I get in console

> Uncaught TypeError: this.$inputor.caret is not a function

![2016-01-12_12-23-19](https://cloud.githubusercontent.com/assets/650741/12256446/50d03b40-b927-11e5-8e1c-3b17e9f6b116.png)

**Comment by ichord** [comment]
did you install the Caret.js lib?

**Comment by Serhioromano** [comment]
No. Should it be installed as dependency?
