### ISSUE TITLE
npm.js contains only 0.5.1 version, the latest is 1.4.0

### ISSUE THREAD

**Issue by iabdulin** [ichord/At.js#374]
https://www.npmjs.com/package/at.js

**Comment by miletbaker** [comment]
You can specify a specific version by using the following cmd, it will then install directly from the github tagged release. i.e. to install 1.4.1 use ```npm install --save ichord/at.js#v1.4.1```

**Comment by iabdulin** [comment]
@miletbaker thanks!

**Comment by thedotedge** [comment]
:+1:

**Comment by kentmw** [comment]
Please update npm! Relying on two dependency repositories (npm and github) is just adding more places of failure.

**Comment by ichord** [comment]
published.
