### ISSUE TITLE
how to accept name with space?

### ISSUE THREAD

**Issue by hendry91** [ichord/At.js#402]
Hi, anyone can guide me how to accept the name with space?
i saw atwho.js matcher function got acceptSpaceBar, but I dunno how to use it.
I try:
```
var user_config = {
at: "@",
matcher: function(flag, subtext, should_start_with_space) {
var match, regexp;
            
flag = flag.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
            
if (should_start_with_space) {
flag = '(?:^|\\s)' + flag;
}

regexp = new RegExp(flag + '([A-Za-z0-9_\\s\+\-\]*)$|' + flag + '([^\\x00-\\xff]*)$', 'gi');
match = regexp.exec(subtext.replace(/\s/g, " "));
if (match) {
return match[2] || match[1];
} else {
return null;
}
},
xxxx...
```
this code, work, but sometime got problem, it wont break/finish the tag when I type without the @tag.
I will get something like `<span class="atwho-inserted" data-atwho-at-query="@">@hendry xxx xxx xxx</span> `instead of `<span class="atwho-inserted" data-atwho-at-query="@">@hendry</span>  xxx xxx xxx`
Another problem is:
1. I type @123
2. popup abc1234, I enter space to continue without select the tag
3. type another @hen
3. popup hendry
4. I press enter/tab to select it, but my output become 

> @hendry

 instead of 

> @123 @hendry 

Thanks.

**Comment by AndyGCook** [comment]
You should be able to just use the `spaceSelectsMatch` option.

I haven't tested your option code, but by setting spaceSelectsMatch = true in the options you should be all set.

```
var user_config = {
at: "@",
spaceSelectsMatch: true,
matcher: function(flag, subtext, should_start_with_space) {
var match, regexp;

flag = flag.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");

if (should_start_with_space) {
flag = '(?:^|\\s)' + flag;
}

**Comment by ichord** [comment]
as @AndyGCook said, thanks @AndyGCook .
