### ISSUE TITLE
Trouble using At.js in TypeScript project

### ISSUE THREAD

**Issue by loicknuchel** [ichord/At.js#406]
Hi, your lib seems fantastic but I didn't succeed unsing it in my [Ionic2](http://ionicframework.com/docs/v2/) project (I use Ionic2, Angular2 & TypeScript) :(

1. I installed jquery, jquery.caret et at.js from npm : `npm install jquery jquery.caret at.js --save` (I've got versions 2.2.4, 0.2.1 & 0.5.1 respectively)
2. I imported typings for jquery : `typings install dt~jquery --ambient --save` (it seems there is none for caret & at.js)

But after that I get troubles : 

-  I'm unable to import them (typescript import) just like jquery (`import * as jQuery from "jquery";`) so I copied them to my project to import the file (`import * as caret from "../../lib/jquery.caret/jquery.caret.min";`)
- When I use them, nothing happens : 
```
jQuery(this._elementRef.nativeElement).find('textarea').atwho({
    at: '@',
    data: ['one', 'two', 'three']
});
```

Do you have any idea on what's going on and how to solve this ?

**Comment by loicknuchel** [comment]
I forgot to add CSS so I didn't saw anything happen...
Now I manually updated to latest versions (caret 0.3.1 & atwho 1.5.0) and it seems to work...
But it's still very badly integrated (libs copied manually in the project...).
Do you know why I can't import them like any other lib ?

Thank you

**Comment by ichord** [comment]
Sorry, I don't know how TypeScript integrating libs.
I would be appreciate if you could try to figure it or give me some information, for it's take time to setting a demo project and simulate your scene.

close it for now for it's not a very serious problem.
