### ISSUE TITLE
Support search for diacritical characters/apostrophes

### ISSUE THREAD

**Issue by erikACTmd** [ichord/At.js#410]
Is there any plans to add support for converting user input that might include diacritics (characters with apostrophes/accents) for search?

Let's say that I am searching for "Åndrea Albee", 
<img width="187" alt="screen shot 2016-06-23 at 10 57 06 am" src="https://cloud.githubusercontent.com/assets/15015575/16308214/13d6d880-3932-11e6-9746-88d3ffd9b12d.png">
but I have a standard English keyboard and if I am typing in "Andrea", it is not matching currently "Åndrea" as At.js is not doing the conversion under the hood for the search.
<img width="200" alt="screen shot 2016-06-23 at 10 57 23 am" src="https://cloud.githubusercontent.com/assets/15015575/16308220/1afb6342-3932-11e6-9e35-87bb864544e6.png">

I have seen https://github.com/brianreavis/sifter.js?files=1 and https://github.com/andrewrk/node-diacritics used for this purpose, perhaps they could be integrated with At.js?

**Comment by ichord** [comment]
You could use the `matcher` callbacks to customize.
Check out the wiki page: https://github.com/ichord/At.js/wiki/Callbacks, or you can search the other issues to learn how to `matcher` callback, such as:

```coffee
$("#inputor").atwho
  at: "@"
  callbacks:
    matcher: ->
      # customize matching
```
