### ISSUE TITLE
how to remove space after insert?

### ISSUE THREAD

**Issue by wlekin** [ichord/At.js#442]
this plugin is great, but i dont want a space after insert, how to disable it?

**Comment by antongorodezkiy** [comment]
For others who will find this issue, space can be removed with a `suffix` setting (more info https://github.com/ichord/At.js/wiki/Base-Document#settings )

**Comment by caoxiaoshuai1** [comment]
how to use suffix? @antongorodezkiy

**Comment by caoxiaoshuai1** [comment]
This is the useful solution https://github.com/ichord/At.js/issues/294
