### ISSUE TITLE
Manually insert text

### ISSUE THREAD

**Issue by thibaultfriedrich** [ichord/At.js#464]
Hi,

I am using At.js and it works very well. However I want to use it with Quill editor. Insertion of text doesn't work so I have to do it myself and I use the field `functionOverrides` : 

```
$(quill.root).atwho({
        at: '@',
        data: ['Peter', 'Anne'],
        displayTpl: "<li>${name}</li>",
        insertTpl: "${name}",
        functionOverrides: {
             insert: function(text, data) {
                    // insertion
             }
       }
});
```
I have to problem to insert but the function `insert` only receives the full text and not only the text to insert.

Examples: if I have already type "@Pe", and choose "Peter" in the dropdown, `insert` receives the text "Peter" and I have no way to get only "eter" or at least what was already written. Do you have any idea how to manually insert with At.js ?

**Comment by danielreed07** [comment]
@thibaultfriedrich Did you have any luck with At.js integration? I'm interested in this as well.

**Comment by adamkdean** [comment]
One way you could do this is:

    var buffer = '';

    $(quill.root).on("shown.atwho", function() {
      buffer = '';
      atwhoMenuActive = true;
    });

    $(quill.root).on("hidden.atwho", function() {
      atwhoMenuActive = false;
    });

    // detect key presses while atwhoMenuActive is true, store in buffer, upon insert, use buffer
