### ISSUE TITLE
How to handle multi thousand usernames?

### ISSUE THREAD

**Issue by Moradnejad** [ichord/At.js#468]
First I have to say that I know how to implement this tool and I haven't found any problem with its current usage.
But I have a problem: I have a large social network with close many thousand people. It is just not possible to load the data at start or refer to _a static json file (as it is currently possible with data option)_.

I wanted to know if it is possible to link to a json url with the current user input, so the server would return only usernames that qualify. **This is more like detecting the input and doing the filtering in the server side.**

Is this option _already supported_ or _should I implement it myself by changing the code_?

**Comment by phorque** [comment]
You should try remoteFilter https://github.com/ichord/At.js/wiki/How-to-use-remoteFilter :cat:

**Comment by Moradnejad** [comment]
thanks
