### ISSUE TITLE
Compatibility with input element?

### ISSUE THREAD

**Issue by AlexDanault** [ichord/At.js#472]
Hi !

The doc says this lib is compatible with textarea and contenteditable, but I need it on a regular input (type=text).

At first everything seems to run perfectly fine (fiddle: http://jsfiddle.net/r59oty6c/ ) but I am wondering if I'm going to run into some trouble in the long run ?

I found it weird that the doc doesn't state support for inputs.

Thanks !

**Comment by ichord** [comment]
The problem is if the input's content is too long, and you have scroll, the view position will be wired.
And I think autocomplete right under the input will be batter interaction for short input, so that I didn't state that.
