### ISSUE TITLE
Allow at least one character after '@' to trigger. 

### ISSUE THREAD

**Issue by arifhussain353** [ichord/At.js#496]
Is there any way to show popup matching at least one character after `@` symbol Or can we use `regex/function return` for specific match string to show popup?

**Comment by markdon** [comment]
We do this in the override for `remoteFilter`.When the `query.length` is less than two characters, execute callback and return empty results.

Check out the `DEFAULT_CALLBACKS `in jquery.atwho.js to see what they're normally doing and the [wiki ](https://github.com/ichord/At.js/wiki/Callbacks)for a tiny bit of documentation.
```
$('#inputor').atwho({
	at : "@",
	data : ['Peter', 'Tom', 'Anne'],
	remoteFilter : function (query, callback) {
		if (query == null || query.length < 2)
			return callback([]);

		//otherwise do xhr and pass result to callback()
	},
	filter : function (query, data, searchKey) {
		if (query == null || query.length < 2)
			return [];
		//otherwise do filter
	}
})
```

**Comment by arifhussain353** [comment]
@markdon  Thank you
