### ISSUE TITLE
How to match without the space before 'at'

### ISSUE THREAD

**Issue by caoxiaoshuai1** [ichord/At.js#500]
It only match when I input with at least a single space, how can I match without space only when it match the keywords?

**Comment by caoxiaoshuai1** [comment]
I have got the solution from the code.

**Comment by Skura23** [comment]
How do you solve it? Can you post your solution?

**Comment by Skura23** [comment]
Ok, I solve it, simply add `startWithSpace: false` in `elm.atwho({..})`.
