### ISSUE TITLE
Froala At.js integration issue.

### ISSUE THREAD

**Issue by NathanDubord** [ichord/At.js#507]
I followed the Froala example and have atjs pretty much working, but there's issues with deleting inserted tags. I noticed the markup is slightly off from the example. This is the markup that's getting inserted:
```<span class="atwho-inserted" data-atwho-at-query="@" contenteditable="false">@Nathan</span>```

Any idea why I'm getting contenteditable="false"?

My config:
```
let config = {
    at: '@',
    data: names,
    displayTpl: '<li>${name} <small>${email}</small></li>',
    limit: 100
};
```

The examples online don't have contenteditable at all.

**Comment by natcohen** [comment]
You should close this and follow this one https://github.com/froala/wysiwyg-editor/issues/2166
