### ISSUE TITLE
Remote dynamic data with filter

### ISSUE THREAD

**Issue by abides** [ichord/At.js#78]
Is it possible to put an example in Examples area about getting remote dynamic data with filter using user input as search term. For example from php including utf-8 chars. I'm not asking php example please don't get me wrong, i just want to know what is the parameter (query string / post) sended to remote data script and how i send it for filter data before retrieve the final json result.

I'm still trying to figure it out how i can do that. Can't find any information about it in examples and issues.

**Comment by andrewtweber** [comment]
@ichord the page "How to use remote_filter" no longer exists. Is this feature still working?

**Comment by philrykoff** [comment]
In case anyone is wondering, the URL for the wiki entry is now https://github.com/ichord/At.js/wiki/How-to-use-remoteFilter.
